Change DSCP to Veritable
digicatapult/dscp-flux-infra pull request #42
Opened 2022-11-25 15:59 UTC by nitro-marky

This renames `DSCP` to `Veritable` where appropriate in markdown files.

2022-11-25 16:02 UTC, dblane-digicatapult requested changes

2022-11-25 16:02 UTC, dblane-digicatapult commented on docs/getting-started.md
> +      version: '0.0.5'
revert

2022-11-25 16:02 UTC, dblane-digicatapult commented on docs/getting-started.md
> +      path: '/api(/|$)(.*)'
revert

2022-12-02 13:27 UTC, jonmattgray approved these changes

2023-08-02 09:06 UTC, closed without merging